---
- hosts: web, api
  gather_facts: no
  become: true
  become_method: sudo

  tasks:

    - name: install python software properties
      apt:
        name: python-software-properties
        state: present

    - name: add repository
      apt_repository:
        repo: ppa:chris-lea/node.js
        state: present

    - name: update repositories
      apt:
        update_cache: yes

    - name: install nodejs
      apt:
        name: nodejs
        state: present